name: Sync SVN to Git

on:
  # Trigger manually from the Actions tab
  workflow_dispatch:

  # Trigger automatically on a schedule (e.g., every hour)
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour

jobs:
  sync:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Install SVN and rsync
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update -y
          sudo apt-get install -y rsync git-svn
          
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Fetch all history so tagging and branching operations work correctly
          fetch-depth: 0
          # Use a Personal Access Token (PAT) if you need to trigger other workflows
          # Or if the default GITHUB_TOKEN doesn't have enough permissions (e.g., cross-repo)
          # token: ${{ secrets.YOUR_PAT }} # Usually not needed for same-repo pushes

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup SSH Agent for Repo-B Access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.OLEX2_GUI_DEPLOY_KEY }}


      - name: Fetch submodules
        run: |
          git submodule update --init --recursive
      
      - name: Cache .git directory
        uses: actions/cache@v4.2.3
        id: cache-git
        path: olex2-gui-git/.git
        key: git-svn-${{ github.sha }} # Use a unique key for initial setup

      - name: Initialize Git SVN (if not already initialized)
        if: steps.cache-git.outputs.cache-hit != 'true'
        run: |
          git svn init --prefix=svn/ --trunk=trunk http://svn.olex2.org/olex2-gui olex2-gui-git
          cd olex2-gui-git 
          git branch -a
          cd ..

      - name: Run SVN to Git Sync Script
        id: sync_script
        run: |
          # Execute your Python script, passing the workspace path as the root path
          python svn-sync.py ${{ github.workspace }}

      - name: Report Failure
        if: steps.sync_script.outcome == 'failure'
        run: echo "SVN Sync script failed. Check logs."
        # Potentially send a notification here
